# Fix vim colors inside tmux
[ -n $TMUX ] && alias vim="TERM=screen-256color vim"

# Put bash in vim mode
set -o vi

# Set default editor to vim
export EDITOR=vim

# Prompt
[ -f $HOME/.bash_prompt ] && source $HOME/.bash_prompt

# Aliases
[ -f $HOME/.aliases_common ] && source $HOME/.aliases_common
[ -f $HOME/.aliases_zsh ] && source $HOME/.aliases_zsh
[ -f $HOME/.aliases_custom ] && source $HOME/.aliases_custom

# Source local extra (private) settings specific to machine if it exists
[ -f $HOME/.bashrc.local ] && source $HOME/.bashrc.local