# Export PATH
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

source $ZSH/oh-my-zsh.sh

# Theme
ZSH_THEME="dracula"

# Hyphen-insensitive completion
HYPHEN_INSENSITIVE="true"

# Plugins
plugins=(zsh-autosuggestions redis-cli sublime sudo zsh-syntax-highlighting)
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh


# User configuration
export EDITOR='vim'
export SSH_KEY_PATH="~/.ssh/id_rsa"

#theme
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(time)
POWERLEVEL9K_TIME_BACKGROUND="black"
POWERLEVEL9K_TIME_FOREGROUND="249"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=4
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='white'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='white'
POWERLEVEL9K_DIR_HOME_FOREGROUND='white'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='white'

#other
export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"

# Aliases
if [ -f ~/.aliases_common ]; then
    source ~/.aliases_common
fi

if [ -f ~/.aliases_zsh ]; then
    source ~/.aliases_zsh
fi

if [ -f ~/.aliases_custom ]; then
    source ~/.aliases_custom
fi
