# Export PATH
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

source $ZSH/oh-my-zsh.sh

# Theme
ZSH_THEME="mitrichius"

# Hyphen-insensitive completion
HYPHEN_INSENSITIVE="true"

# Plugins
plugins=(zsh-autosuggestions redis-cli sublime sudo zsh-syntax-highlighting)
source $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# User configuration
export EDITOR='vim'
export SSH_KEY_PATH="$HOME/.ssh/id_rsa"

#other
export NVM_DIR="$HOME/.nvm"
[ -f /usr/local/opt/nvm/nvm.sh ] && source "/usr/local/opt/nvm/nvm.sh"

# Aliases
[ -f $HOME/.aliases_common ] && source $HOME/.aliases_common
[ -f $HOME/.aliases_zsh ] && source $HOME/.aliases_zsh
[ -f $HOME/.aliases_custom ] && source $HOME/.aliases_custom

# Source local extra (private) settings specific to machine if it exists
[ -f $HOME/.zshrc.local ] && source $HOME/.zshrc.local