# Theme
ZSH_THEME="mitrichius"

# Hyphen-insensitive completion
HYPHEN_INSENSITIVE="true"

# Plugins
ZSH_AUTOSUGGEST_USE_ASYNC=true
plugins=(zsh-autosuggestions per-directory-history)

# Export PATH
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

source $ZSH/oh-my-zsh.sh

# User configuration
export EDITOR='vim'
export SSH_KEY_PATH="$HOME/.ssh/id_rsa"

# History
export HISTSIZE=1000000
export SAVEHIST=1000000
setopt share_history
setopt hist_ignore_all_dups
setopt hist_no_store
setopt hist_reduce_blanks
setopt inc_append_history
setopt extended_history
setopt hist_ignore_space

#other
export NVM_DIR="$HOME/.nvm"
[ -f /usr/local/opt/nvm/nvm.sh ] && source "/usr/local/opt/nvm/nvm.sh"

# Aliases
[ -f $HOME/.aliases_common ] && source $HOME/.aliases_common
[ -f $HOME/.aliases_zsh ] && source $HOME/.aliases_zsh
[ -f $HOME/.aliases_local ] && source $HOME/.aliases_local

# Source local extra (private) settings specific to machine if it exists
[ -f $HOME/.zshrc.local ] && source $HOME/.zshrc.local
